resources:
- repo: self
queue:
  name: DocFX
steps:
- powershell@2: ./impact.ps1
  arguments: '-GitHubPAT $(GitHubPAT)'
  displayName: 'Impact Test'

- powershell@2: ./build.ps1
  displayName: Build

- task: NuGetCommand@2
  displayName: 'Push to MyGet'
  inputs:
    command: push
    packagesToPush: 'drop/**/*.nupkg'
    nuGetFeedType: external
    publishFeedCredentials: 'myget.docfx-v3'
