resources:
- repo: self
queue:
  name: DocFX
steps:
- powershell: ./impact.ps1
  env:
    GitHubPAT: $(GitHubPAT)
    DevOpsPAT: $(DevOpsPAT)
    SYSTEM_ACCESS_TOKEN: $(System.AccessToken)
  displayName: 'Impact Test'

- powershell: ./build.ps1
  displayName: Build

- task: NuGetCommand@2
  displayName: 'Push to MyGet'
  inputs:
    command: push
    packagesToPush: 'drop/**/*.nupkg'
    nuGetFeedType: external
    publishFeedCredentials: 'myget.docfx-v3'
